---
name: a8n-tools-dev

services:

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: a8n-tools-frontend
    restart: unless-stopped
    env_file:
      - path: ./frontend/.env
        required: false
    environment:
      # Docker-specific overrides (API is on host-mapped port 18080)
      VITE_API_URL: ${VITE_API_URL:-http://localhost:18080}
      VITE_APP_DOMAIN: ${VITE_APP_DOMAIN:-localhost}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/index.html:/app/index.html:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/postcss.config.js:/app/postcss.config.js:ro

  # Rust API Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: a8n-tools-api
    restart: unless-stopped
    env_file:
      - path: ./api/.env
        required: false
    environment:
      # Docker-specific overrides
      DATABASE_URL: postgres://a8n:${POSTGRES_PASSWORD:-devpassword}@postgres:5432/a8n_platform
      RUST_LOG: ${RUST_LOG:-debug}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173}
      ENVIRONMENT: development
      STRIPE_SUCCESS_URL: ${APP_URL:-http://localhost:5173}/checkout/success
      STRIPE_CANCEL_URL: ${APP_URL:-http://localhost:5173}/pricing?checkout=canceled
    ports:
      - "18080:8080"
    volumes:
      - ./api/src:/app/src:ro
      - ./api/migrations:/app/migrations:ro
      - ./api/templates:/app/templates:ro
      - ./api/Cargo.toml:/app/Cargo.toml:ro
      - ./api/Cargo.lock:/app/Cargo.lock:ro
      - api_target:/app/target
    depends_on:
      postgres:
        condition: service_healthy

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: a8n-tools-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: a8n
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
      POSTGRES_DB: a8n_platform
    expose:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U a8n -d a8n_platform"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  # postgres_data:
  data:
  api_target:
