---
# Build OCI image and push to Forgejo Container Registry.
name: Build OCI container

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
    #paths:
    #  - "oci-build/**"
    #  - ".forgejo/workflows/build-oci-image.yml"

# TODO: Remove debug env vars once CI is stable.
env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build-and-push:
    name: Build and push saas image
    runs-on: opensuse-base-16.0-v1
    permissions:
      contents: read
      packages: write
    env:
      # Image registry and registry user are set in the steps below.
      IMAGE_REGISTRY: ""
      REGISTRY_PROVIDER: dev.a8n.run
      REGISTRY_USER: ""
      REGISTRY_PASSWORD: ${{ secrets.FORGEJO_PAT }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # The repository owner needs to be lowercase.
      - name: Set environment variables
        shell: nu {0}
        run: |
          let owner = ($env.GITHUB_REPOSITORY_OWNER | str downcase)
          $"REGISTRY_USER=($owner)\n" | save --append $env.GITHUB_ENV
          $"IMAGE_REGISTRY=($env.REGISTRY_PROVIDER)/($owner)\n" | save --append $env.GITHUB_ENV

      - name: Build saas image
        id: build-image
        shell: nu {0}
        run: |
          cd oci-build
          ./build.nu

      # TODO: Remove this debug step once CI is stable.
      - name: Debug environment before push
        shell: nu {0}
        run: |
          print "=== Registry env vars ==="
          print $"REGISTRY_PROVIDER: ($env.REGISTRY_PROVIDER)"
          print $"REGISTRY_USER: ($env.REGISTRY_USER)"
          print $"REGISTRY_PASSWORD length: ($env.REGISTRY_PASSWORD | str length)"
          print $"IMAGE_REGISTRY: ($env.IMAGE_REGISTRY)"
          print ""
          print "=== Build outputs ==="
          print "image: ${{ steps.build-image.outputs.image }}"
          print "tags: ${{ steps.build-image.outputs.tags }}"
          print ""
          print "=== Secrets context ==="
          print '${{ toJson(secrets) }}'
          print ""
          print "=== Env context ==="
          print '${{ toJson(env) }}'

      # Uses buildah directly since podman is not installed on the runner.
      # Switch to redhat-actions/push-to-registry@v2 once podman is available.
      - name: Push image to Forgejo Container Registry
        id: push-to-forgejo
        shell: nu {0}
        run: |
          # Print the command for debugging (mask the password)
          let password_masked = ($env.REGISTRY_PASSWORD | str substring 0..3) + "***"
          print $"DEBUG: buildah login --username ($env.REGISTRY_USER) --password ($password_masked) ($env.REGISTRY_PROVIDER)"
          ^buildah login --username $env.REGISTRY_USER --password $env.REGISTRY_PASSWORD $env.REGISTRY_PROVIDER
          let image = "${{ steps.build-image.outputs.image }}"
          let tags_str = "${{ steps.build-image.outputs.tags }}"
          let tags = ($tags_str | split row ",")
          let registry = $env.IMAGE_REGISTRY
          let registry_paths = ($tags | each {|tag|
            let dest = $"docker://($registry)/($image):($tag)"
            print $"Pushing ($image):($tag) to ($dest)"
            ^buildah push $"($image):($tag)" $dest
            $"($registry)/($image):($tag)"
          } | str join ",")
          $"registry-paths=($registry_paths)\n" | save --append $env.GITHUB_OUTPUT

      - name: Print image URLs
        shell: nu {0}
        run: |
          let paths = "${{ steps.push-to-forgejo.outputs.registry-paths }}"
          for path in ($paths | split row ",") {
            print $"Image pushed to ($path)"
          }
