---
# Reusable workflow for building and pushing images.
name: Build and push image

on:
  workflow_call:
    inputs:
      dir-name:
        description: 'Name of directory to build'
        required: true
        type: string
      image-name:
        description: 'Name of image to build'
        required: true
        type: string
    outputs:
      registry-paths:
        description: 'Registry paths where the image was pushed'
        value: ${{ jobs.build-and-push.outputs.registry-paths }}

# TODO: Remove debug env vars once CI is stable.
env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build-and-push:
    name: Build and push ${{ inputs.image-name }} image
    # Use the label from the Forgejo runner
    runs-on: opensuse-base-16.0-v1
    permissions:
      contents: read
      packages: write
    env:
      # Image registry and registry user are set in the steps below.
      IMAGE_REGISTRY: ""
      REGISTRY_PROVIDER: dev.a8n.run
      REGISTRY_USER: ""
      REGISTRY_PASSWORD: ${{ secrets.FORGEJO_PAT }}
    outputs:
      registry-paths: ${{ steps.push-to-forgejo.outputs.registry-paths }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      # Use Nushell for all scripts.
      #- name: Install Nushell
      #  id: nushell
      #  uses: https://codeberg.org/NiceGuyIT/action-install-nushell@main
      #  with:
      #    nushell-version: '0.101.0'
      #    register-plugins: true

      # The repository owner needs to be lowercase.
      - name: Set environment variables
        shell: nu {0}
        run: |
          let owner = ($env.GITHUB_REPOSITORY_OWNER | str downcase)
          $"REGISTRY_USER=($owner)\n" | save --append $env.GITHUB_ENV
          $"IMAGE_REGISTRY=($env.REGISTRY_PROVIDER)/($owner)\n" | save --append $env.GITHUB_ENV

      - name: Build ${{ inputs.image-name }} image
        id: build-image
        shell: nu {0}
        run: |
          cd ${{ inputs.dir-name }}
          ./build.nu

      # TODO: Remove this debug step once CI is stable.
      - name: Debug environment before push
        shell: nu {0}
        run: |
          print "=== Registry env vars ==="
          print $"REGISTRY_PROVIDER: ($env.REGISTRY_PROVIDER)"
          print $"REGISTRY_USER: ($env.REGISTRY_USER)"
          print $"REGISTRY_PASSWORD length: ($env.REGISTRY_PASSWORD | str length)"
          print $"IMAGE_REGISTRY: ($env.IMAGE_REGISTRY)"
          print ""
          print "=== Build outputs ==="
          print "image: ${{ steps.build-image.outputs.image }}"
          print "tags: ${{ steps.build-image.outputs.tags }}"
          print ""
          print "=== Secrets context ==="
          print '${{ toJson(secrets) }}'
          print ""
          print "=== Env context ==="
          print '${{ toJson(env) }}'

      # Uses buildah directly since podman is not installed on the runner.
      # Switch to redhat-actions/push-to-registry@v2 once podman is available.
      - name: Push image to Forgejo Container Registry
        id: push-to-forgejo
        shell: nu {0}
        run: |
          # Print the command for debugging (mask the password)
          let password_masked = ($env.REGISTRY_PASSWORD | str substring 0..3) + "***"
          print $"DEBUG: buildah login --username ($env.REGISTRY_USER) --password ($password_masked) ($env.REGISTRY_PROVIDER)"
          ^buildah login --username $env.REGISTRY_USER --password $env.REGISTRY_PASSWORD $env.REGISTRY_PROVIDER
          let image = "${{ steps.build-image.outputs.image }}"
          let tag = "${{ steps.build-image.outputs.tags }}"
          let registry = $env.IMAGE_REGISTRY
          let dest = $"docker://($registry)/($image):($tag)"
          print $"DEBUG: buildah push ($image):($tag) ($dest)"
          ^buildah push $"($image):($tag)" $dest
          $"registry-paths=($registry)/($image):($tag)\n" | save --append $env.GITHUB_OUTPUT

      - name: Print image URL
        run: echo "Production image pushed to ${{ steps.push-to-forgejo.outputs.registry-paths }}"
