name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  secrets:
    runs-on: ${{ vars.RUNS_ON_OPENSUSE_BASE_MEDIUM }}
    steps:
      - name: Rename .gitconfig
        # The runner's ~/.gitconfig prevents actions/checkout from working.
        shell: nu {0}
        run: |
          let gitconfig = ([$env.HOME .gitconfig] | path join)
          if ($gitconfig | path expand | path exists) {
            mv $gitconfig ([$gitconfig 'disabled'] | str join '-')
          }

      - name: Clone the repository
        uses: https://code.forgejo.org/actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Secrets scan
        uses: https://dev.a8n.run/psa-systems/common/.forgejo/actions/check-secrets@main
